sudo: required

language: cpp
compiler: gcc

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-random-dev
  - sudo apt-get install mlocate
  - pip install --user cpp-coveralls

script: 
  - mkdir build
  - cd build
  - cmake ..
  - cp ../pot_example.txt .
  - cp ../pot_example.txt ./test
  - cp ../pot_example.txt ./Testing
  - make
  - make test
  - make catch

