language: cpp

script: 
  - mkdir build
  - cd build
  - cmake ..
  - cp ../pot_example.txt .
  - cp ../pot_example.txt ./test
  - cp ../pot_example.txt ./Testing
  - cp ../pot_example.txt Testing/Temporary
  - make
  - make test
  - make catch
  - make coverage


