language: cpp

script: 
  - mkdir build
  - cd build
  - cmake ..
  - cp ../test/pot_example.txt ./test/pot_example.txt
  - cp ../test/pot_example.txt ./pot_example.txt
  - cp ../test/pot_example.txt ./bin/pot_example.txt
  - make
  - make test



after_success: 
  - bash <(curl -s https://codecov.io/bash)
