language: cpp

script: 
  - mkdir build
  - cd build
  - cmake ..
  - cp ../pot_example.txt .
  - cp ../pot_example.txt ./test
  - cp ../pot_example.txt ./Testing
  - make
  - chmod u+rw ../src/CMakeFiles/sharedlib.dir/langevin.cpp.gcov
  - make test
  - make catch

after_success:
  - make coverage


