sudo: required

language: cpp
compiler: g++

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-random-dev
  - sudo apt-get install mlocate

script: 
  - mkdir build
  - cd build
  - cmake ..
  - cp ../pot_example.txt .
  - cp ../pot_example.txt ./test
  - cp ../pot_example.txt ./Testing
  - make

  - make test
  - make catch

after_success:
  - sudo updatedb
  - printf "Testing langevin.cpp for coverage...\n"
  - GCOV_PATH=`locate -i langevin.cpp.gcno | sed -n 1p | sed -e 's/\/langevin.cpp.gcno//g'`
  - printf "(gcov files can be found at ${GCOV_PATH})\n"
  - sudo chmod a+rw $GCOV_PATH/langevin.cpp.gcno
  - sudo gcov $GCOV_PATH/langevin.cpp.gcov -n | grep langevin.cpp\' -A1









